# mkdocs.yml
site_name: "TS Bolt"
site_author: L Ma
site_description: "Time Series Nuts and Bolts"
site_url: "https://emptymalei.github.io/ts-bolt"
repo_url: "https://github.com/emptymalei/ts-bolt"
edit_uri: "blob/main/docs/"
repo_name: "emptymalei/ts-bolt"


theme:
  name: "material"
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  logo: assets/logo_transparent.png



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "¤"

plugins:
  - autorefs
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            filters:



extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - "Home": index.md
  - "Tutorials":
    - "Introduction": tutorials/index.md
    - "Command Line Tool": tutorials/command-line.md
    - "Use Pandas DataFrame": tutorials/pandas-dataframe.md
  - References:
    - "Introduction": references/index.md
    - "Data Modules":
        - "GluonTS": references/datamodules/gluonts.md
        - "Pandas": references/datamodules/pandas.md
    - "Datasets":
        - "Collections": references/datasets/collections.md
        - "Downloaders":
          - "Base": references/datasets/downloaders/base.md
          - "Exchange Rate": references/datasets/downloaders/ecb_exchange_rate.md
    - "Evaluation":
        - "Evaluator": references/evaluation/evaluator.md
    - "Naive Forecaster":
        - "Last Observation": references/naive_forecasters/last_observation.md
    - "CLI": references/cli.md
    - "Changelog": changelog.md
