name: Publish Docs
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
    inputs:
      whotriggered:
        description: 'Manually Build Docs'
        default: 'Just want to build it'
        required: false

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.3.2
      - name: Install Packages
        run: poetry install
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Deploy
        run: poetry run mkdocs gh-deploy --force
